"""crud final

Revision ID: 08754570837a
Revises: 08856ff255cf
Create Date: 2021-09-07 12:19:04.316543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08754570837a'
down_revision = '08856ff255cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
