"""cascade delete

Revision ID: 08856ff255cf
Revises: 642da89818c0
Create Date: 2021-09-06 13:50:43.512716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08856ff255cf'
down_revision = '642da89818c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
