"""mariadb db transfer from postgresql

Revision ID: a3ab54c05e0d
Revises: d280d9ac4512
Create Date: 2021-09-06 09:29:30.366295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ab54c05e0d'
down_revision = 'd280d9ac4512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
